
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(MASS)
library(tidyverse)
library(ggplot2)
library(ggthemes)
library(ggspatial)
library(geoR)
library(akima)
library(fields)
library(sp)
library(raster)
library(scales)
library(haven)
library(mnormt)
library(plotly)
library(rayshader)
library(gridExtra)
library(forecast)
library(viridis)
library(plot3D)
library(demogR)
library(spatial)
library(sf)
library(spdep)
library(Matrix)
```

# Problem 1

```{r}
load("Admin1Geography.RData")
load("Admin2Geography.RData")

# # saveRDS(nigeriaAdm1, "Admin1Geography.rds")
# # saveRDS(nigeriaAdm2, "Admin2Geography.rds")
# 
# nigeriaAdm1 <- readRDS("Admin1Geography.rds")
# nigeriaAdm2 <- readRDS("Admin2Geography.rds")

Admin1Graph <- read.csv("Admin1Graph.txt", sep = "")
Admin2Graph <- read.csv("Admin2Graph.txt", sep = "")
```

## a)


```{r}
structure_matrix <- function(graph) return(diag(rowSums(graph), nrow = nrow(graph), ncol = ncol(graph)) - graph)

precision_matrix <- function(graph, tau) return(tau * structure_matrix(graph))

sparse_df <- function(matrix) {
  
  matrix[matrix != 0] <- "non-zero"
  matrix[matrix == 0] <- "zero"
  
  df <- data.frame(x = as.factor(rep(1:nrow(matrix), each = ncol(matrix))), "x names" = rep(rownames(matrix), each = ncol(matrix)), y = as.factor(rep(1:ncol(matrix), nrow(matrix))), "y names" = rep(rownames(matrix), each = ncol(matrix)), value = as.factor(as.vector(as.matrix(matrix))))
  
  return(df)
}

names <- rownames(Admin1Graph)

sparsity_plot <- function(matrix, names) {
  df <- sparse_df(matrix)
  df_names <- unique(df$x.names)
  
  namess <- numeric(length(df_names))
  for (i in as.numeric(unique(df$x))) {
    namess[i] <- gsub("\\:.*", "", (df_names[i]))
  }
  
  names_df <- data.frame(name = as.factor(names), min_position = as.vector(sapply(names, function(i) min(which(str_detect(namess, i))))), max_position = as.vector(sapply(names, function(i) max(which(str_detect(namess, i))))))
  
  names_df <- names_df %>% mutate(position = as.integer((min_position + max_position) / 2), left_line = min_position - .5, right_line = max_position + .5)
  
  return(ggplot(df) +
           geom_raster(aes(x = x, y = y, fill = value)) +
           # geom_vline(xintercept = unique(c(names_df$left_line, names_df$right_line)), linewidth = .5, color = "gray") +
           # geom_hline(yintercept = unique(c(names_df$left_line, names_df$right_line)), linewidth = .5, color = "gray") +
           coord_fixed() +
           scale_fill_manual(values = c("non-zero" = "#7E0020", "zero" = "#FFFFC9")) +
           scale_x_discrete(breaks = names_df$position, labels = names_df$name) +
           scale_y_discrete(breaks = names_df$position, labels = names_df$name, limits = rev) +
           theme(
             axis.text = element_text(size = 8, margin = unit(0.5, "cm")),
             axis.title = element_blank(),
             legend.title = element_text(size = 15),
             legend.text = element_text(size = 14),
             legend.position = "none",
             axis.line = element_line(colour = "black"),
             axis.ticks = element_line(linewidth = 1),
             axis.ticks.length = unit(0.3, "cm"),
             axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5),
             panel.background = element_blank(),
             panel.grid.major = element_blank(),
             panel.grid.minor = element_blank(),
           ))
}

Q_1_sparsity_plot <- sparsity_plot(precision_matrix(Admin1Graph, 1), names)
Q_2_sparsity_plot <- sparsity_plot(precision_matrix(Admin2Graph, 1), names)

Q_1_sparsity_plot
Q_2_sparsity_plot

# ggsave("Figs/Problem 1/a)/Q_1_sparsity_plot.png", Q_1_sparsity_plot, width = 25, height = 25, unit = "cm")
# ggsave("Figs/Problem 1/a)/Q_2_sparsity_plot.png", Q_2_sparsity_plot, width = 25, height = 25, unit = "cm")

test1 <- precision_matrix(Admin1Graph, 1)
test1[test1 != 0] <- 1
sum(colSums(test1))/prod(dim(test1))

test2 <- precision_matrix(Admin2Graph, 1)
test2[test2 != 0] <- 1
sum(colSums(test2))/prod(dim(test2))
```

## b)

```{r}
sim_IGMRF_fun <- function(Q, epsilon, seed) {
  set.seed(seed)
  Q_tilde <- Q + epsilon * diag(1, nrow(Q), ncol(Q))
  L_tilde <- t(chol(Q_tilde))
  z <- rnorm(nrow(Q))
  v <- solve(t(L_tilde), z)
  x <- v - mean(v)
  return(as.vector(x))
}

sim_GMRF_fun <- function(mu, Q, seed) {
  set.seed(seed)
  L <- t(chol(Q))
  z <- rnorm(nrow(Q))
  v <- solve(t(L), z)
  x <- mu + v
  return(x)
}

sim_fun_plot <- function(map, x, limits = NULL, lab = "Value") {
  
  if (is.null(limits)) limits <- range(x)
  
  map$x <- x
  return(ggplot() +
           geom_sf(aes(fill = x),
                   data = map,
                   color = "gray") +
           scale_fill_viridis_c(direction = -1, limits = limits) +
           guides(fill = guide_colorbar(lab, label = T, ticks = F, barwidth = 1, barheight = 20)) +
           theme(
             axis.text = element_text(size = 15, margin = unit(0.5, "cm")),
             axis.title = element_blank(),
             legend.title = element_text(size = 15),
             legend.text = element_text(size = 14),
             # legend.position = "none",
             axis.line = element_line(colour = "black"),
             axis.ticks = element_line(linewidth = 1),
             axis.ticks.length = unit(0.3, "cm"),
             axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5),
             # panel.background = element_blank(),
             # panel.grid.major = element_blank(),
             # panel.grid.minor = element_blank(),
           ))
}

admin1_tau_1_sim_seed_1 <- sim_IGMRF_fun(precision_matrix(Admin1Graph, 1), 1e-6, 1)
admin1_tau_1_sim_seed_2 <- sim_IGMRF_fun(precision_matrix(Admin1Graph, 1), 1e-6, 2)
mv_gaussian_dim_37_mean_0_cov_1_seed_1 <- sim_GMRF_fun(0, solve(diag(1, 37, 37)), 1)
mv_gaussian_dim_37_mean_0_cov_1_seed_2 <- sim_GMRF_fun(0, solve(diag(1, 37, 37)), 2)

plot_b_range <- range(admin1_tau_1_sim_seed_1, admin1_tau_1_sim_seed_2, mv_gaussian_dim_37_mean_0_cov_1_seed_1, mv_gaussian_dim_37_mean_0_cov_1_seed_2)

admin1_tau_1_sim_seed_1_plot <- sim_fun_plot(nigeriaAdm1, admin1_tau_1_sim_seed_1, plot_b_range)
admin1_tau_1_sim_seed_2_plot <- sim_fun_plot(nigeriaAdm1, admin1_tau_1_sim_seed_2, plot_b_range)

mv_gaussian_dim_37_mean_0_cov_1_seed_1_plot <- sim_fun_plot(nigeriaAdm1, mv_gaussian_dim_37_mean_0_cov_1_seed_1, plot_b_range)
mv_gaussian_dim_37_mean_0_cov_1_seed_2_plot <- sim_fun_plot(nigeriaAdm1, mv_gaussian_dim_37_mean_0_cov_1_seed_2, plot_b_range)

admin1_tau_1_sim_seed_1_plot
admin1_tau_1_sim_seed_2_plot

mv_gaussian_dim_37_mean_0_cov_1_seed_1_plot
mv_gaussian_dim_37_mean_0_cov_1_seed_2_plot

# ggsave("Figs/Problem 1/b)/admin1_tau_1_sim_seed_1_plot.png", admin1_tau_1_sim_seed_1_plot, width = 25, height = 20, unit = "cm")
# ggsave("Figs/Problem 1/b)/admin1_tau_1_sim_seed_2_plot.png", admin1_tau_1_sim_seed_2_plot, width = 25, height = 20, unit = "cm")
# ggsave("Figs/Problem 1/b)/mv_gaussian_dim_37_mean_0_cov_1_seed_1_plot.png", mv_gaussian_dim_37_mean_0_cov_1_seed_1_plot, width = 25, height = 20, unit = "cm")
# ggsave("Figs/Problem 1/b)/mv_gaussian_dim_37_mean_0_cov_1_seed_2_plot.png", mv_gaussian_dim_37_mean_0_cov_1_seed_2_plot, width = 25, height = 20, unit = "cm")
```

## c)

```{r}
admin2_tau_1_sim_seed_1 <- sim_IGMRF_fun(precision_matrix(Admin2Graph, 1), 1e-6, 1)
admin2_tau_1_sim_seed_2 <- sim_IGMRF_fun(precision_matrix(Admin2Graph, 1), 1e-6, 2)
mv_gaussian_dim_775_mean_0_cov_1_seed_1 <- sim_GMRF_fun(0, solve(diag(1, 775, 775)), 1)
mv_gaussian_dim_775_mean_0_cov_1_seed_2 <- sim_GMRF_fun(0, solve(diag(1, 775, 775)), 2)

plot_c_range <- range(admin2_tau_1_sim_seed_1, admin2_tau_1_sim_seed_2, mv_gaussian_dim_775_mean_0_cov_1_seed_1, mv_gaussian_dim_775_mean_0_cov_1_seed_2)

admin2_tau_1_sim_seed_1_plot <- sim_fun_plot(nigeriaAdm2, admin2_tau_1_sim_seed_1, plot_c_range)
admin2_tau_1_sim_seed_2_plot <- sim_fun_plot(nigeriaAdm2, admin2_tau_1_sim_seed_2, plot_c_range)

mv_gaussian_dim_775_mean_0_cov_1_seed_1_plot <- sim_fun_plot(nigeriaAdm2, mv_gaussian_dim_775_mean_0_cov_1_seed_1, plot_c_range)
mv_gaussian_dim_775_mean_0_cov_1_seed_2_plot <- sim_fun_plot(nigeriaAdm2, mv_gaussian_dim_775_mean_0_cov_1_seed_2, plot_c_range)

admin2_tau_1_sim_seed_1_plot
admin2_tau_1_sim_seed_2_plot

mv_gaussian_dim_775_mean_0_cov_1_seed_1_plot
mv_gaussian_dim_775_mean_0_cov_1_seed_2_plot

# ggsave("Figs/Problem 1/c)/admin2_tau_1_sim_seed_1_plot.png", admin2_tau_1_sim_seed_1_plot, width = 25, height = 20, unit = "cm")
# ggsave("Figs/Problem 1/c)/admin2_tau_1_sim_seed_2_plot.png", admin2_tau_1_sim_seed_2_plot, width = 25, height = 20, unit = "cm")
# ggsave("Figs/Problem 1/c)/mv_gaussian_dim_775_mean_0_cov_1_seed_1_plot.png", mv_gaussian_dim_775_mean_0_cov_1_seed_1_plot, width = 25, height = 20, unit = "cm")
# ggsave("Figs/Problem 1/c)/mv_gaussian_dim_775_mean_0_cov_1_seed_2_plot.png", mv_gaussian_dim_775_mean_0_cov_1_seed_2_plot, width = 25, height = 20, unit = "cm")
```

## d)

```{r}
sim_n_IGMRF_fun <- function(Q, epsilon = 1e-6, n = 100) {
  df <- data.frame(matrix(nrow = n, ncol = nrow(Q)))
  colnames(df) <- rownames(Q)
  
  for (i in 1:n) df[i,] <- sim_IGMRF_fun(Q, epsilon, i)
  
  return(df)
}

admin2_tau_1_100_sim <- sim_n_IGMRF_fun(precision_matrix(Admin2Graph, 1))
admin2_tau_1_100_sim_cov <- cov(admin2_tau_1_100_sim)
admin2_tau_1_100_sim_cor <- cor(admin2_tau_1_100_sim)
admin2_tau_1_100_sim_var_plot <- sim_fun_plot(nigeriaAdm2, diag(admin2_tau_1_100_sim_cov), lab = "Var")
admin2_tau_1_100_sim_cor_plot <- sim_fun_plot(nigeriaAdm2, admin2_tau_1_100_sim_cor[150,], lab = "Cor")

admin2_tau_1_100_sim_var_plot
admin2_tau_1_100_sim_cor_plot

# ggsave("Figs/Problem 1/d)/admin2_tau_1_100_sim_var_plot.png", admin2_tau_1_100_sim_var_plot, width = 25, height = 20, unit = "cm")
# ggsave("Figs/Problem 1/d)/admin2_tau_1_100_sim_cor_plot.png", admin2_tau_1_100_sim_cor_plot, width = 25, height = 20, unit = "cm")
```

# Problem 2

```{r}
DirectEstimates <- read.csv("DirectEstimates.txt", sep = "")
```

## a)

```{r}
p_hat <- plogis(DirectEstimates$Observation)

p_hat_plot <- sim_fun_plot(nigeriaAdm1, p_hat, c(0, 1), lab = "Prob.")

p_hat_plot

# ggsave("Figs/Problem 2/a)/p_hat_plot.png", p_hat_plot, width = 25, height = 20, unit = "cm")
```

## b)

```{r}
sim_n_expit_GMRF_fun <- function(mu, Q, n = 100) {
  df <- data.frame(matrix(nrow = n, ncol = nrow(Q)))
  colnames(df) <- colnames(Q)
  
  for (i in 1:n) df[i,] <- plogis(sim_GMRF_fun(mu, Q, i))
  
  return(df)
}

V <- diag(DirectEstimates$StdDev^2, 37, 37)
colnames(V) <- rownames(V) <- DirectEstimates$Admin1

sim_100_expit_GMRF <- sim_n_expit_GMRF_fun(DirectEstimates$Observation, solve(V))
sim_100_expit_GMRF_median <- apply(sim_100_expit_GMRF, 2, median)
sim_100_expit_GMRF_coef_var <- apply(sim_100_expit_GMRF, 2, sd) / apply(sim_100_expit_GMRF, 2, mean)

sim_100_expit_GMRF_median_plot <- sim_fun_plot(nigeriaAdm1, sim_100_expit_GMRF_median, c(0, 1), lab = "Median")
sim_100_expit_GMRF_coef_var_plot <- sim_fun_plot(nigeriaAdm1, sim_100_expit_GMRF_coef_var, c(0, .4), lab = "Coef. \nVar.")

sim_100_expit_GMRF_median_plot
sim_100_expit_GMRF_coef_var_plot

# ggsave("Figs/Problem 2/b)/sim_100_expit_GMRF_median_plot.png", sim_100_expit_GMRF_median_plot, width = 25, height = 20, unit = "cm")
# ggsave("Figs/Problem 2/b)/sim_100_expit_GMRF_coef_var_plot_revised.png", sim_100_expit_GMRF_coef_var_plot, width = 25, height = 20, unit = "cm")
```

## c)

```{r}
cond_mu_vector_fun <- function(Q_1, M, Q_2, y) return(solve(Q_1 + t(M) %*% Q_2 %*% M) %*% t(M) %*% Q_2 %*% y)
cond_Precision_matrix_fun <- function(Q_1, M, Q_2) return(Q_1 + t(M) %*% Q_2 %*% M)

sim_n_conditional_expit_GMRF_fun <- function(y, M, Q_1, Q_2, n) {
  df <- data.frame(matrix(nrow = n, ncol = nrow(Q_1)))
  colnames(df) <- colnames(Q_1)
  
  mu <- cond_mu_vector_fun(Q_1, M, Q_2, y)
  Q <- cond_Precision_matrix_fun(Q_1, M, Q_2)
  
  for (i in 1:n) df[i,] <- plogis(sim_GMRF_fun(mu, Q, i))
  
  return(df)
}

sim_100_expit_GMRF_c <- sim_n_conditional_expit_GMRF_fun(DirectEstimates$Observation, diag(1, 37, 37), precision_matrix(Admin1Graph, 1), solve(V), 100)

sim_100_expit_GMRF_c_median <- apply(sim_100_expit_GMRF_c, 2, median)
sim_100_expit_GMRF_c_coef_var <- apply(sim_100_expit_GMRF_c, 2, sd) / apply(sim_100_expit_GMRF_c, 2, mean)

sim_100_expit_GMRF_c_median_plot <- sim_fun_plot(nigeriaAdm1, sim_100_expit_GMRF_c_median, c(0, 1), lab = "Median")
sim_100_expit_GMRF_c_coef_var_plot <- sim_fun_plot(nigeriaAdm1, sim_100_expit_GMRF_c_coef_var, c(0, .4), lab = "Coef. \nVar.")

sim_100_expit_GMRF_c_median_plot
sim_100_expit_GMRF_c_coef_var_plot

# ggsave("Figs/Problem 2/c)/sim_100_expit_GMRF_c_median_plot.png", sim_100_expit_GMRF_c_median_plot, width = 25, height = 20, unit = "cm")
# ggsave("Figs/Problem 2/c)/sim_100_expit_GMRF_c_coef_var_plot_revised.png", sim_100_expit_GMRF_c_coef_var_plot, width = 25, height = 20, unit = "cm")

rankMatrix(as.matrix(cond_Precision_matrix_fun(precision_matrix(Admin1Graph, 1), diag(1, 37, 37), solve(V))))

det(as.matrix(cond_Precision_matrix_fun(precision_matrix(Admin1Graph, 1), diag(1, 37, 37), solve(V))))
```

## d)

```{r}
M <- diag(1, 38, 37)
M[38,] <- c(rep(0, 18), 1, rep(0, 18))

sim_100_expit_GMRF_d <- sim_n_conditional_expit_GMRF_fun(c(DirectEstimates$Observation, .5), M, precision_matrix(Admin1Graph, 1), solve(diag(c(DirectEstimates$StdDev^2, .1^2), 38, 38)), 100)

sim_100_expit_GMRF_d_median <- apply(sim_100_expit_GMRF_d, 2, median)
sim_100_expit_GMRF_d_coef_var <- apply(sim_100_expit_GMRF_d, 2, sd) / apply(sim_100_expit_GMRF_d, 2, mean)

sim_100_expit_GMRF_d_median_plot <- sim_fun_plot(nigeriaAdm1, sim_100_expit_GMRF_d_median, c(0, 1), lab = "Median")
sim_100_expit_GMRF_d_coef_var_plot <- sim_fun_plot(nigeriaAdm1, sim_100_expit_GMRF_d_coef_var, c(0, .4), lab = "Coef. \nVar.")

sim_100_expit_GMRF_d_median_plot
sim_100_expit_GMRF_d_coef_var_plot

# ggsave("Figs/Problem 2/d)/sim_100_expit_GMRF_d_median_plot_revised.png", sim_100_expit_GMRF_d_median_plot, width = 25, height = 20, unit = "cm")
# ggsave("Figs/Problem 2/d)/sim_100_expit_GMRF_d_coef_var_plot_revised.png", sim_100_expit_GMRF_d_coef_var_plot, width = 25, height = 20, unit = "cm")
```

## e)

```{r}
sim_100_expit_GMRF_tau_0.1 <- sim_n_conditional_expit_GMRF_fun(DirectEstimates$Observation, diag(1, 37, 37), precision_matrix(Admin1Graph, .1), solve(V), 100)
sim_100_expit_GMRF_tau_10 <- sim_n_conditional_expit_GMRF_fun(DirectEstimates$Observation, diag(1, 37, 37), precision_matrix(Admin1Graph, 10), solve(V), 100)

sim_100_expit_GMRF_tau_0.1_median <- apply(sim_100_expit_GMRF_tau_0.1, 2, median)
sim_100_expit_GMRF_tau_0.1_coef_var <- apply(sim_100_expit_GMRF_tau_0.1, 2, sd) / apply(sim_100_expit_GMRF_tau_0.1, 2, mean)
sim_100_expit_GMRF_tau_10_median <- apply(sim_100_expit_GMRF_tau_10, 2, median)
sim_100_expit_GMRF_tau_10_coef_var <- apply(sim_100_expit_GMRF_tau_10, 2, sd) / apply(sim_100_expit_GMRF_tau_10, 2, mean)

sim_100_expit_GMRF_tau_0.1_median_plot <- sim_fun_plot(nigeriaAdm1, sim_100_expit_GMRF_tau_0.1_median, c(0, 1), lab = "Median")
sim_100_expit_GMRF_tau_0.1_coef_var_plot <- sim_fun_plot(nigeriaAdm1, sim_100_expit_GMRF_tau_0.1_coef_var, c(0, .4), lab = "Coef. \nVar.")
sim_100_expit_GMRF_tau_10_median_plot <- sim_fun_plot(nigeriaAdm1, sim_100_expit_GMRF_tau_10_median, c(0, 1), lab = "Median")
sim_100_expit_GMRF_tau_10_coef_var_plot <- sim_fun_plot(nigeriaAdm1, sim_100_expit_GMRF_tau_10_coef_var, c(0, .4), lab = "Coef. \nVar.")

sim_100_expit_GMRF_tau_0.1_median_plot
sim_100_expit_GMRF_tau_0.1_coef_var_plot
sim_100_expit_GMRF_tau_10_median_plot
sim_100_expit_GMRF_tau_10_coef_var_plot

# ggsave("Figs/Problem 2/e)/sim_100_expit_GMRF_tau_0.1_median_plot.png", sim_100_expit_GMRF_tau_0.1_median_plot, width = 25, height = 20, unit = "cm")
# ggsave("Figs/Problem 2/e)/sim_100_expit_GMRF_tau_0.1_coef_var_plot_revised.png", sim_100_expit_GMRF_tau_0.1_coef_var_plot, width = 25, height = 20, unit = "cm")
# ggsave("Figs/Problem 2/e)/sim_100_expit_GMRF_tau_10_median_plot.png", sim_100_expit_GMRF_tau_10_median_plot, width = 25, height = 20, unit = "cm")
# ggsave("Figs/Problem 2/e)/sim_100_expit_GMRF_tau_10_coef_var_plot_revised.png", sim_100_expit_GMRF_tau_10_coef_var_plot, width = 25, height = 20, unit = "cm")
```

## f)

```{r}
log_likelihood_fun <- function(tau, x, y, R, D) {
  Q_C <- cond_Precision_matrix_fun(as.matrix(precision_matrix(Admin1Graph, tau)), diag(1, 37, 37), solve(D))
  mu_C <- cond_mu_vector_fun(precision_matrix(Admin1Graph, tau), diag(1, 37, 37), solve(D), y)
  
  
  return(((37 - 1)/2) * log(tau) - (tau/2) * t(x) %*% R %*% x - (1/2) * t(y - x) %*% solve(D) %*% (y - x) - (1/2) * log(det(Q_C)) + (1/2) * t(x - mu_C) %*% Q_C %*% (x - mu_C))
}

x <- numeric(37)
y <- DirectEstimates$Observation
R <- as.matrix(structure_matrix(Admin1Graph))
D <- V

opt_tau <- optimize(log_likelihood_fun, c(0, 100), x = x, y = y, R = R, D = D, maximum = TRUE)
# opt_tau$maximum

sim_100_expit_GMRF_tau_optimal <- sim_n_conditional_expit_GMRF_fun(DirectEstimates$Observation, diag(1, 37, 37), precision_matrix(Admin1Graph, opt_tau$maximum), solve(V), 100)

sim_100_expit_GMRF_tau_optimal_median <- apply(sim_100_expit_GMRF_tau_optimal, 2, median)
sim_100_expit_GMRF_tau_optimal_coef_var <- apply(sim_100_expit_GMRF_tau_optimal, 2, sd) / apply(sim_100_expit_GMRF_tau_optimal, 2, mean)

sim_100_expit_GMRF_tau_optimal_median_plot <- sim_fun_plot(nigeriaAdm1, sim_100_expit_GMRF_tau_optimal_median, c(0, 1), lab = "Median")
sim_100_expit_GMRF_tau_optimal_coef_var_plot <- sim_fun_plot(nigeriaAdm1, sim_100_expit_GMRF_tau_optimal_coef_var, c(0, .4), lab = "Coef. \nVar.")

sim_100_expit_GMRF_tau_optimal_median_plot
sim_100_expit_GMRF_tau_optimal_coef_var_plot

# ggsave("Figs/Problem 2/f)/sim_100_expit_GMRF_tau_optimal_median_plot.png", sim_100_expit_GMRF_tau_optimal_median_plot, width = 25, height = 20, unit = "cm")
# ggsave("Figs/Problem 2/f)/sim_100_expit_GMRF_tau_optimal_coef_var_plot_revised.png", sim_100_expit_GMRF_tau_optimal_coef_var_plot, width = 25, height = 20, unit = "cm")
```
